-- AlterTable
ALTER TABLE "Country" ADD COLUMN     "acceptedLanguageTests" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "accommodationTypes" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "applicationTimeline" TEXT,
ADD COLUMN     "averageRentMax" DOUBLE PRECISION,
ADD COLUMN     "averageRentMin" DOUBLE PRECISION,
ADD COLUMN     "costOfLivingCurrency" TEXT,
ADD COLUMN     "costOfLivingMax" DOUBLE PRECISION,
ADD COLUMN     "costOfLivingMin" DOUBLE PRECISION,
ADD COLUMN     "dependentVisaAvailable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "gapAcceptance" TEXT,
ADD COLUMN     "hasHalalFood" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasVegetarianFood" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "healthcareDetails" TEXT,
ADD COLUMN     "images" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "internationalStudentPopulation" TEXT,
ADD COLUMN     "majorIntakes" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "overviewEn" TEXT,
ADD COLUMN     "overviewRu" TEXT,
ADD COLUMN     "overviewUz" TEXT,
ADD COLUMN     "partTimeWorkHours" TEXT,
ADD COLUMN     "postStudyWorkDuration" TEXT,
ADD COLUMN     "prPathwayAvailable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "proofOfFundsAmount" TEXT,
ADD COLUMN     "rentCurrency" TEXT,
ADD COLUMN     "safetyIndex" TEXT,
ADD COLUMN     "scholarshipAvailability" TEXT,
ADD COLUMN     "standardizedTestsRequired" TEXT,
ADD COLUMN     "tuitionCurrency" TEXT,
ADD COLUMN     "tuitionMax" DOUBLE PRECISION,
ADD COLUMN     "tuitionMin" DOUBLE PRECISION,
ADD COLUMN     "visaAcceptanceRate" TEXT,
ADD COLUMN     "visaInterviewRequired" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "visaProcessingTime" TEXT;
